### ISSUE TITLE
Mycroft does not recognize skill

### ISSUE THREAD

**Issue by Colonial-Dev** [MycroftAI/skill-alarm#36]
When asking Mycroft to set an alarm, Mycroft simply says that "I might want to say it differently" or a similar message (meaning the command is not recognized.)

Uninstalling/reinstalling the alarm skill does not solve the problem. I am using the Mycroft version available through the Ubuntu snap store, although the git install method produces the same issue.

**Comment by penrods** [comment]
I'm not familiar with the Ubuntu Snap -- this was added by a community member.  What does it report when you say "Hey Mycroft, what version are you running?"

**Comment by Colonial-Dev** [comment]
Removing everything and installing from the git repo fixed the issue. Sorry to bother you

**Comment by penrods** [comment]
No bother, good to be aware of this Snap package.

I'm going to go ahead and close this issue.
