### ISSUE TITLE
Long-term alarms get a weird response

### ISSUE THREAD

**Issue by valdr** [MycroftAI/skill-alarm#41]
I was attempting to set an alarm for the 18 october 2018, and although the alarm seems to have been set, the response I got "I've created an alarm for today at midnight, 30 days from now" seems a bit strange.

Setting an alarm for somewhere within the week is fine, as you can see on the screenshot.
I've spoken with Ake and Kathy on chat. Kathy asked me to create this issue.

![strange_snipped](https://user-images.githubusercontent.com/1840006/45748583-806aa380-bc09-11e8-8ce1-d69e2a8d294f.png)

**Comment by KathyReid** [comment]
OK, I tried to replicate this but couldn't. 
![screenshot from 2018-09-20 16-29-00](https://user-images.githubusercontent.com/114158/45815895-602c0900-bd1d-11e8-875a-517ef8a10859.png)

I'm running a new commit - are you on the same commit; 

```
kathyreid@kathyreid-Oryx-Pro:/opt/mycroft/skills/mycroft-alarm.mycroftai$ git log
commit e6ccee38f67a3eaa4f3d50ea0963b7d70a485c4c (HEAD -> 18.08, origin/18.08)
Author: Steve Penrod <github@gpll.org>
Date:   Mon Sep 17 04:09:16 2018 -0500

    Fix to deal with systems that aren't in UTC timezone (#40)
    
    The Alarm only worked correctly when the base OS was in UTC timezone.  This
    fixes it for all timezones.
    
    Also improved the reporting of nice_relative_time() by rounding the chosen unit.

```

**Comment by forslund** [comment]
I can get if for some dates:

```
 set alarm on october 21
 >> Alarm set for tomorrow at midnight, in 30 days
```

Seems to be weird for dates that are 28, 29 and 30 days away...

I'm at commit e6ccee38f67a3eaa4f3d50ea0963b7d70a485c4c

**Comment by penrods** [comment]
Fixed by this: https://github.com/MycroftAI/mycroft-core/pull/1827

**Comment by forslund** [comment]
Closing this as the issue has men resolved.
