### ISSUE TITLE
Stopping an alarm requires wake word, does not give listening sound

### ISSUE THREAD

**Issue by ekjswim** [MycroftAI/skill-alarm#65]
Without announcing the listening sound, catching when the listening is active to stop the alarm is difficult to figure out and thus it's hard to stop the alarm. I'd suggest making it the same as Timer skill where there's plenty of time in between buzzes.

**Comment by davbl** [comment]
I'd say accept "stop" without the wake word to stop a beeping alarm (and timer).

**Comment by ekjswim** [comment]
I can't think of anything else in Mycroft that happens without so signifier/expectation of listening. Converse skills play the listening sound and animation when looking for input, and of course, a wake word provides an expectation of being listened to, and may or may not provide the audio and visual feedback that it's listening.
