### ISSUE TITLE
Alarm skill goes off but sound does not play

### ISSUE THREAD

**Issue by ChanceNCounter** [MycroftAI/skill-alarm#71]
Linux Mint 19.3, core-dev, alarm skill's up to date.

I get a lot of this:

```
Playing MPEG stream 1 of 1: constant_beep.mp3 ...

MPEG 1.0 L III cbr128 44100 stereo

Title:   Digital Alarm Clock Sound Effect
Artist:  audioman5000
Album:   https://freesound.org/people/israra/sounds/434055/
Year:    20180121

[0:05] Decoding of constant_beep.mp3 finished.
High Performance MPEG 1.0/2.0/2.5 Audio Player for Layers 1, 2 and 3
        version 1.25.10; written and copyright by Michael Hipp and others
        free software (LGPL) without any warranty but with best wishes
```

but no audio.

Instructions for what logs to pull or etc. would be appreciated. I'm unfamiliar with the external utilities at play.

**Comment by krisgesling** [comment]
Hey Chance - this clearly got missed... 

Does this work on the latest Linux Mint? If unsure I think we just close it for now. I assume it was an issue with the playback of mp3's rather than an issue with the Alarm Skill?

**Comment by ChanceNCounter** [comment]
I missed that reply, too =P

Indeed, I haven't booted into Mint in ages.
