### ISSUE TITLE
Cannot stop a alarm that is sounding, endless loop, need to reinstall the whole app 

### ISSUE THREAD

**Issue by baditaflorin** [MycroftAI/skill-alarm#97]
1. I cannot copy the output from the app. So I cannot provide any usefull informations. this is unproductive for debugging. 
2. set an alarm, now the voice commands do not work, getting the alarm every 10 seconds or so.
 
![image](https://user-images.githubusercontent.com/2330999/83953965-9725b380-a84d-11ea-9eed-f95ad3b6f5a2.png)

**Comment by krisgesling** [comment]
Hi there,

Was "sfo" transcribed from your speech?

If you type "stop" into the CLI and hit enter this should stop all the alarms.

You can also find the relevant logs in `/var/log/myroft/` or ask Mycroft to "create a support ticket" and it will package up your logs and email you a link to them.

**Comment by krisgesling** [comment]
Closing this ticket as without more info we can't do any more on this. 

Feel free to reopen if you are still seeing the issue.
